//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Loja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produtos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produtos()
        {
            this.Produtos1 = new HashSet<Produtos>();
        }
    
        public long id_prod_pk { get; set; }
        public string desc_prod { get; set; }
        public string cod_barras { get; set; }
        public long fk_cat { get; set; }
        public decimal valor { get; set; }
        public decimal qtd_prod { get; set; }
        public long fk_prod_super { get; set; }
        public byte[] data_cri_prod { get; set; }
        public Nullable<System.DateTime> data_att_prod { get; set; }
        public byte status { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produtos> Produtos1 { get; set; }
        public virtual Produtos Produtos2 { get; set; }
    }
}
